### ISSUE TITLE
ThreadPool.cc 疑似BUG

### ISSUE THREAD

**Issue by abbycin** [lucklove/ahttpd#16]
ThreadPool.hh里面的worker是`std::vector<std::thread> workers`
#### 在构造函数中

``` c++
ThreadPool::ThreadPool(size_t n, std::function<void()> on_enter, std::function<void()> on_exit)
    : workers(n)
{
    for(size_t i = 0; i < n; ++i)
        workers.emplace_back([=]{
            if(on_enter)
                on_enter();
            while(true)
            {
```
#### 在析构函数中

``` c++
for(auto& worker : workers)
            try
            {
                worker.join();
            }
            catch(std::system_error&)
            {}
```

有给这个workers指定大小n，但是在函数体里面却是`emplace_back`，这样的话:
- 如果n是0，循环不会进，池子大小是0，无意义  
- 如果n大于0，那么池子的大小将会是2n，在析构函数中前面n个`worker.join()`可能会`segmentation fault`

**Comment by FrankHB** [comment]
[Upstream](https://github.com/FrankHB/YSLib/blob/e6acf460a618336a12143adf6589535de722ab17/YBase/source/ystdex/concurrency.cpp#L52) confirmed.

Will fix the wrong `vector` initialization in next build commit.

Note it won't have `segmentation fault` since [it is required to throw `std::system_error`](http://www.eel.is/c++draft/thread.thread.member#6) exception [when `join()` called on a thread which is not joinable](http://www.eel.is/c++draft/thread.thread.member#7), and then it is caught by the `catch` clause.

The bug was introduced [at the very first revision](https://github.com/FrankHB/YSLib/blob/f2fc97cfd56bc6de56652571667ba41d8f1d6095/YBase/source/ystdex/concurrency.cpp#L37). It would not have effect in the first revision because [there was a `joinable` check](https://github.com/FrankHB/YSLib/blob/f2fc97cfd56bc6de56652571667ba41d8f1d6095/YBase/source/ystdex/concurrency.cpp#L74). It was changed in [this revision](https://github.com/FrankHB/YSLib/commit/46d4ac01fe1a1d0dbe2c42addb77d2339a8d5d4f).

So the program will keep well-defined behavior. No observable damage should be detected.

Zero-sized pool is valid since it is expected [to be handled in client code when necessary](https://github.com/FrankHB/YSLib/blob/e6acf460a618336a12143adf6589535de722ab17/YBase/include/ystdex/concurrency.h#L211), so it will remain current behavior.

**Comment by lucklove** [comment]
已确认并修复，thx

**Comment by abbycin** [comment]
@FrankHB 为何不这样呢？

``` c++
#include <chrono>
#include <vector>
#include <thread>
#include <iostream>

class Test
{
  public:
    Test(int n): pool()
    {
      for(int i = 0; i < n; ++i)
      {
        pool.emplace_back([]
            {
              auto s = std::chrono::seconds(1);
              std::this_thread::sleep_for(s);
            });
      }
    }
    ~Test()
    {
      for(auto& x: pool)
        x.join();
    }
    std::size_t size()
    {
      return pool.size();
    }
  private:
    std::vector<std::thread> pool;
};

int main()
{
  Test t(10);
}
```

**Comment by FrankHB** [comment]
@abbycin 怎么添加任务？

**Comment by abbycin** [comment]
@FrankHB 我看了下头文件，这里添加任务和池子没关系啊，只是需要注意同步，并且一旦创建了对象，池子的大小就固定了啊。
所以，你说“怎么添加任务？”是想表达什么呢？

**Comment by FrankHB** [comment]
@abbycin 池的大小是指工作线程的数量，这个是初始化时固定的。但负载不是固定的，是得在创建池之后 `enqueue` 进去的，而且显然在这个项目中被用到了。

**Comment by FrankHB** [comment]
[Upstream fixed.](https://github.com/FrankHB/YSLib/commit/6997ac9a72421f0e1120a8f938bf62016ed39541)
